% -------------------------------------------------------------------
%  Generated by MATLAB on 4-Dec-2018 16:08:10
%  MATLAB version: 9.5.0.944444 (R2018b)
% -------------------------------------------------------------------
saveVarsMat = load('load_data.mat');

L = saveVarsMat.L; % <1x7 Link> unsupported class

Robot = saveVarsMat.Robot; % <1x1 SerialLink> unsupported class

a = [0.069 0 0.069 0 0.01 0 0];

alpha = [-1.5707963267948966 1.5707963267948966 -1.5707963267948966 ...
    1.5707963267948966 -1.5707963267948966 1.5707963267948966 0];

d = [0.2703 0 0.3644 0 0.3743 0 0.2295];

i = 7;

m = [5.70044 3.22698 4.31272 2.07206 2.24665 1.60879];

q = [0 0 0 0 0 0 0];

smiData = struct;
smiData.RigidTransform = struct;
smiData.RigidTransform(1).translation = ...
  [-41.037908318391416 -48.353409537746934 0];
smiData.RigidTransform(1).angle = 2.0943951023931953;
smiData.RigidTransform(1).axis = [0.57735026918962584 -0.57735026918962584 ...
                                  0.57735026918962584];
smiData.RigidTransform(1).ID = 'B[Arm0-2:-:Arm1-2]';
smiData.RigidTransform(2).translation = ...
  [-41.091479005755808 -48.7259738419582 -7.1054273576010019E-15];
smiData.RigidTransform(2).angle = 2.0943951023931953;
smiData.RigidTransform(2).axis = [0.57735026918962584 -0.57735026918962584 ...
                                  0.57735026918962584];
smiData.RigidTransform(2).ID = 'F[Arm0-2:-:Arm1-2]';
smiData.RigidTransform(3).translation = ...
  [-34.139802623438563 -20.882500814536204 6.008076915750002];
smiData.RigidTransform(3).angle = 3.1415926535897931;
smiData.RigidTransform(3).axis = [1 0 0];
smiData.RigidTransform(3).ID = 'B[Arm1-2:-:Arm2-2]';
smiData.RigidTransform(4).translation = ...
  [-33.58527724662757 -20.770773087905248 6.0080769157499816];
smiData.RigidTransform(4).angle = 3.1415926535897927;
smiData.RigidTransform(4).axis = [-1 2.183819804968178E-32 -9.882683367379622E-17 ...
                                  ];
smiData.RigidTransform(4).ID = 'F[Arm1-2:-:Arm2-2]';
smiData.RigidTransform(5).translation = ...
  [-24.850594178472495 -11.202815758355044 0];
smiData.RigidTransform(5).angle = 2.5627709115243746;
smiData.RigidTransform(5).axis = [-0.67503046152752522 -0.2977713082549639 ...
                                  -0.67503046152752533];
smiData.RigidTransform(5).ID = 'B[Arm2-2:-:Arm3-2]';
smiData.RigidTransform(6).translation = ...
  [-24.850603698441496 -11.202807067480933 -0.00040289153481154472];
smiData.RigidTransform(6).angle = 2.5627709115243746;
smiData.RigidTransform(6).axis = [-0.67503046152752566 -0.2977713082549644 ...
                                  -0.67503046152752433];
smiData.RigidTransform(6).ID = 'F[Arm2-2:-:Arm3-2]';
smiData.RigidTransform(7).translation = ...
  [-1.0337762202090373 1.8692624086248444 6.0080769157500074];
smiData.RigidTransform(7).angle = 3.1415926535897931;
smiData.RigidTransform(7).axis = [1 0 1.3877787807814457E-16];
smiData.RigidTransform(7).ID = 'B[Arm3-2:-:Arm4-2]';
smiData.RigidTransform(8).translation = ...
  [-1.0272888589762896 1.7787771693481371 6.0080769157499869];
smiData.RigidTransform(8).angle = 3.1415926535897922;
smiData.RigidTransform(8).axis = [-1 -4.5416255291573819E-31 7.7478630811879708E-16 ...
                                  ];
smiData.RigidTransform(8).ID = 'F[Arm3-2:-:Arm4-2]';
smiData.RigidTransform(9).translation = ...
  [0.60069565006743986 3.4430086073882094 0];
smiData.RigidTransform(9).angle = 1.721729116952387;
smiData.RigidTransform(9).axis = [0.36153450562429873 -0.85941003164146734 ...
                                  0.36153450562429884];
smiData.RigidTransform(9).ID = 'B[Arm4-2:-:Arm5-2]';
smiData.RigidTransform(10).translation = ...
  [0.600695650067544 3.4430086073883994 -6.6613381477509392E-15];
smiData.RigidTransform(10).angle = 1.7217291169523872;
smiData.RigidTransform(10).axis = [0.36153450562429873 -0.85941003164146734 ...
                                   0.36153450562429862];
smiData.RigidTransform(10).ID = 'F[Arm4-2:-:Arm5-2]';
smiData.RigidTransform(11).translation = ...
  [27.658603605585341 29.28015413127687 5.3405128139999984];
smiData.RigidTransform(11).angle = 3.1415926535897931;
smiData.RigidTransform(11).axis = [1 0 0];
smiData.RigidTransform(11).ID = 'B[Arm5-2:-:ARM6_NEW-2]';
smiData.RigidTransform(12).translation = ...
  [1.1065282098501075 2.4591439995447217E-13 -2.1399548799649892E-13];
smiData.RigidTransform(12).angle = 2.0943951023931957;
smiData.RigidTransform(12).axis = [0.57735026918962573 0.57735026918962584 ...
                                   0.57735026918962573];
smiData.RigidTransform(12).ID = 'F[Arm5-2:-:ARM6_NEW-2]';
smiData.RigidTransform(13).translation = ...
  [6.4487923624927088 -0.51159649838509735 11.355000000000004];
smiData.RigidTransform(13).angle = 3.1415926535897931;
smiData.RigidTransform(13).axis = [1 0 0];
smiData.RigidTransform(13).ID = 'B[ARM6_NEW-2:-:Arm6Part2-2]';
smiData.RigidTransform(14).translation = ...
  [1.1102230246251565E-15 8.3820000000000157 0];
smiData.RigidTransform(14).angle = 2.0943951023931948;
smiData.RigidTransform(14).axis = [-0.57735026918962562 -0.57735026918962618 ...
                                   -0.57735026918962562];
smiData.RigidTransform(14).ID = 'F[ARM6_NEW-2:-:Arm6Part2-2]';
smiData.RigidTransform(15).translation = ...
  [42.199171751847253 61.100252832435764 15.218064586037682];
smiData.RigidTransform(15).angle = 0;
smiData.RigidTransform(15).axis = [0 0 0];
smiData.RigidTransform(15).ID = 'RootGround[Arm0-2]';
smiData.Solid = struct;
smiData.Solid(1).mass = 1.8124288781461484;
smiData.Solid(1).CoM = [6.4506446418153383 -0.19657360276990288 2.7593387957428059 ...
                        ];
smiData.Solid(1).MoI = [60.016623103912238 69.234432705015863 44.061640068848178 ...
                        ];
smiData.Solid(1).PoI = [1.8403670184220908 0.0096588947480064774 -0.0010830593483394928 ...
                        ];
smiData.Solid(1).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(1).opacity = 1;
smiData.Solid(1).ID = 'ARM6_NEW*:*Default';
smiData.Solid(2).mass = 5.67763020521304;
smiData.Solid(2).CoM = [-6.0985749455638913 -0.43571288638488465 -3.5053594969702389E-5 ...
                        ];
smiData.Solid(2).MoI = [54.537818973981942 56.62265108456802 84.529786989711837 ...
                        ];
smiData.Solid(2).PoI = [-7.5931162949696124E-5 0.00047884155020431438 -23.436499561290141 ...
                        ];
smiData.Solid(2).color = [1 1 1];
smiData.Solid(2).opacity = 0.4;
smiData.Solid(2).ID = 'Arm3*:*Default';
smiData.Solid(3).mass = 2.997534071210433;
smiData.Solid(3).CoM = [-0.0595804231451029 1.0528471081451547 3.6158388213994052E-7 ...
                        ];
smiData.Solid(3).MoI = [21.560827436737895 21.484792681436538 15.639530544095189 ...
                        ];
smiData.Solid(3).PoI = [1.5135865836918628E-5 4.5539100390478864E-6 -1.7262826146152319 ...
                        ];
smiData.Solid(3).color = [0.29411764705882354 0.29411764705882354 0.29411764705882354 ...
                          ];
smiData.Solid(3).opacity = 1;
smiData.Solid(3).ID = 'Arm4*:*Default';
smiData.Solid(4).mass = 3.8593054812783589;
smiData.Solid(4).CoM = [-12.382090252788625 -7.2567881168377317 -6.7111172878598063E-5 ...
                        ];
smiData.Solid(4).MoI = [31.149156261417225 30.194625008531457 26.880125860860083 ...
                        ];
smiData.Solid(4).PoI = [0.0002384724831912601 0.00022004848379802 -5.22925215389204 ...
                        ];
smiData.Solid(4).color = [0.69411764705882351 0.094117647058823528 0.094117647058823528 ...
                          ];
smiData.Solid(4).opacity = 1;
smiData.Solid(4).ID = 'Arm2*:*Default';
smiData.Solid(5).mass = 6.7403464093279624;
smiData.Solid(5).CoM = [-16.720445295332986 -12.880651361649491 -0.0070605149424290805 ...
                        ];
smiData.Solid(5).MoI = [100.38463461757803 45.06409364111601 101.90671330781028 ...
                        ];
smiData.Solid(5).PoI = [-0.059629297989634684 0.11601295177327559 5.9944414674058812 ...
                        ];
smiData.Solid(5).color = [0.29411764705882354 0.29411764705882354 0.29411764705882354 ...
                          ];
smiData.Solid(5).opacity = 1;
smiData.Solid(5).ID = 'Arm1*:*Default';
smiData.Solid(6).mass = 3.831880001460124;
smiData.Solid(6).CoM = [5.8886472752176306 7.1301188491797154 -4.4447177926006253E-6 ...
                        ];
smiData.Solid(6).MoI = [30.550098125433273 30.850018832110695 47.716686217616143 ...
                        ];
smiData.Solid(6).PoI = [3.6167212395273293E-5 -4.8447448489705869E-5 -16.890384655982402 ...
                        ];
smiData.Solid(6).color = [0.69411764705882351 0.094117647058823528 0.094117647058823528 ...
                          ];
smiData.Solid(6).opacity = 1;
smiData.Solid(6).ID = 'Arm5*:*Default';
smiData.Solid(7).mass = 1.0788777716417328;
smiData.Solid(7).CoM = [-0.10067539807388304 2.8668912362611656 0];
smiData.Solid(7).MoI = [22.258271017554183 16.142591281885853 23.021947506303352 ...
                        ];
smiData.Solid(7).PoI = [0 0 -0.71295588385764908];
smiData.Solid(7).color = [0.792156862745098 0.81960784313725488 0.93333333333333335 ...
                          ];
smiData.Solid(7).opacity = 1;
smiData.Solid(7).ID = 'Arm6Part2*:*Default';
smiData.Solid(8).mass = 0.10863414045719302;
smiData.Solid(8).CoM = [-16.156632121786 -20.540181564728154 0];
smiData.Solid(8).MoI = [0.33712085159918 0.33288713014663751 0.34568575239689148 ...
                        ];
smiData.Solid(8).PoI = [0 0 6.4663151367572821E-7];
smiData.Solid(8).color = [0.66666666666666663 0.69803921568627447 0.76862745098039209 ...
                          ];
smiData.Solid(8).opacity = 1;
smiData.Solid(8).ID = 'Arm0*:*Default';
smiData.RevoluteJoint = struct;
smiData.RevoluteJoint(1).Rz = struct;
smiData.RevoluteJoint(1).Rz.Pos = 123.90488358615734;
smiData.RevoluteJoint(1).ID = '[Arm0-2:-:Arm1-2]';
smiData.RevoluteJoint(2).Rz = struct;
smiData.RevoluteJoint(2).Rz.Pos = 6.4076928057049631;
smiData.RevoluteJoint(2).ID = '[Arm1-2:-:Arm2-2]';
smiData.RevoluteJoint(3).Rz = struct;
smiData.RevoluteJoint(3).Rz.Pos = 68.604873613398311;
smiData.RevoluteJoint(3).ID = '[Arm2-2:-:Arm3-2]';
smiData.RevoluteJoint(4).Rz = struct;
smiData.RevoluteJoint(4).Rz.Pos = 107.41701043351819;
smiData.RevoluteJoint(4).ID = '[Arm3-2:-:Arm4-2]';
smiData.RevoluteJoint(5).Rz = struct;
smiData.RevoluteJoint(5).Rz.Pos = -1.5176396123696692;
smiData.RevoluteJoint(5).ID = '[Arm4-2:-:Arm5-2]';
smiData.RevoluteJoint(6).Rz = struct;
smiData.RevoluteJoint(6).Rz.Pos = 163.89014748366625;
smiData.RevoluteJoint(6).ID = '[Arm5-2:-:ARM6_NEW-2]';
smiData.RevoluteJoint(7).Rz = struct;
smiData.RevoluteJoint(7).Rz.Pos = -77.7964275180196;
smiData.RevoluteJoint(7).ID = '[ARM6_NEW-2:-:Arm6Part2-2]';

clear saveVarsMat;
